# Generated by Django 5.2.6 on 2025-09-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('Car_brand', models.CharField(max_length=15)),
                ('Car_model', models.CharField(max_length=10)),
                ('Car_type', models.CharField(max_length=8)),
                ('VIN_no', models.CharField(max_length=17, primary_key=True, serialize=False)),
            ],
        ),
    ]
