# Generated by Django 5.2.6 on 2025-09-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_db',
            name='Seat_count',
            field=models.IntegerField(default=0),
        ),
    ]
